baseURL = 'https://blog.jarexibackblaze.xyz'
languageCode = 'en-us'
title = "Soulfire's Wacky Web"
[params]
    subtitle = 'A wacky blog by a wacky wolf'
    rssFullContent = true

    [params.contact]
        email = 'soulfire@jarexibackblaze.xyz'
    [params.sidebar]
      subtitle = "A wacky blog by a wacky wolf"

[menu]
  main = [ ]


  # Github Social Link
  [[menu.social]]
  identifier = "github"
  name = "GitHub"
  url = "https://github.com/s0ulf3re"
  
  [menu.social.params]
  icon = "brand-github"

  # Mastodon Social Link
  [[menu.social]]
  identifier = "mastodon"
  name = "Mastodon"
  url = "https://wetdry.world/@Soulfirethewolf"

  [menu.social.params]
  icon = "brand-mastodon"

  # Bluesky Social Link
  [[menu.social]]
  identifier = "bluesky"
  name = "Bluesky"
  url = "https://bsky.app/profile/soulfire.jarexibackblaze.xyz"
  
  [menu.social.params]
  icon = "brand-bluesky"

  # Website Social Link
  [[menu.social]]
  identifier = "main-website"
  name = "Main Website"
  url = "https://soulfire.jarexibackblaze.xyz"
  
  [menu.social.params]
  icon = "world"

  # FA Social Link
  [[menu.social]]
  identifier = "fur-affinity"
  name = "Fur Affinity"
  url = "https://furaffinity.net/user/dunked0n"
  
  [menu.social.params]
  icon = "paw"


[[params.widgets.page]]
  type = "toc"
  [params.widgets.page.params]
    limit = 10

[[params.widgets.page]]
  type = "tag-cloud"
  [params.widgets.page.params]
    limit = 10

[[params.widgets.homepage]]
  type = "tag-cloud"
  [params.widgets.homepage.params]
    limit = 10

[[params.widgets.page]]
  type = "search"

[[params.widgets.homepage]]
  type = "search"

[params.opengraph.twitter]
card = "summary_large_image"

[markup.goldmark.renderer]
unsafe = true

[[module.imports]]
path = "github.com/CaiJimmy/hugo-theme-stack/v3"

[caches]
  [caches.images]
    dir = ':cacheDir/images'


[permalinks]
  post = "/:year/:month/:day/:title/"