# This is a basic workflow to help you get started with Actions

name: prepare-posts-for-generation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update-files:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: configure git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout main
          git fetch origin

      # Gets the latest changes from the newest commit
      - name: Get all changed markdown files
        id: changed-markdown-files
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47
        with: 
          files: "content/post/*/*.md"

      - name: setup python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13
          cache: pip
      - run: pip install -r requirements.txt
      
      - name: Apply changes to each markdown file
        if: steps.changed-markdown-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-markdown-files.outputs.all_changed_files }}
        run: |
          IFS=$'\n'
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file"
            python3 scripts/prep-folder-for-publishing.py --file-path "$file"
          done
          unset IFS


      - name: Add changed files to new commit
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-markdown-files.outputs.all_changed_files }}
        run: |
          IFS=$'\n'

          for file in ${ALL_CHANGED_FILES}; do
            git add "$file"
          done
          unset IFS
      - name: Commit new files to repository
        run: |
          git commit -m "Revising commited Markdown files for Hugo"

      - name: Push changes
        run: git push origin main